package com.github.sunnybat.commoncode.startup;

/**
 * A loading window. Useful when doing lengthy tasks that the entire program depends on and doesn't have a Status GUI yet.
 *
 * @author Sunny
 */
public class LoadingWindow extends javax.swing.JFrame {

  /**
   * Creates new form Startup
   */
  public LoadingWindow() {
    this("Program");
  }

  public LoadingWindow(final String title) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        initComponents();
        customComponents(title);
      }
    });
  }

  private void customComponents(String title) {
    setLocationRelativeTo(null);
    try {
      javax.swing.JLabel picLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(getClass().getResource("/com/github/sunnybat/commoncode/startup/Loading.gif")));
      JPPicture.add(picLabel);
      pack();
    } catch (Exception iOException) {
      iOException.printStackTrace();
    }
    if (title != null) {
      jLabel1.setText(title + " is Starting");
      setTitle(title + " Starting");
    }
  }

  /**
   * Makes the window visible.
   */
  public void showWindow() {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        setVisible(true);
      }
    });
  }

  /**
   * Sets the Status Text. This should represent what the program is currently doing.
   *
   * @param text The text to set
   */
  public void setStatus(final String text) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        JLStatus.setText(text);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    JLStatus = new javax.swing.JLabel();
    JPPicture = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Program Starting");
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Program is Starting");

    JLStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    JLStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    JLStatus.setText("Starting up...");

    JPPicture.setLayout(new java.awt.GridLayout(1, 0));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(JLStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addComponent(JPPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(JLStatus)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(JPPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel JLStatus;
  private javax.swing.JPanel JPPicture;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
